name: Build docker

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ {arch: 'x86_64', platform: 'linux/amd64'}, {arch: 'aarch64', platform: 'linux/arm64'}]
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            a1ex4/st-reborn-server
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.targets.platform }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
            arch=${{ matrix.targets.arch }}
          platforms: ${{ matrix.targets.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
